const quizquestions = [{question: "The Eiffel Tower is located where in Paris?",
  answers: ["Bois de Boulogne","Champ de Mars","Jardin des Plantes","Parc de Belleville"],
  answer: 1},
{question: "Which Apollo mission landed the first humans on the Moon?",
  answers: ["Apollo 7","Apollo 9","Apollo 11","Apollo 13"],
  answer: 2},
{question: "Who starred in the 1959 epic film 'Ben-Hur'?",
  answers: ["Charlton Heston","Clark Gable","Errol Flynn","Lee Marvin"],
  answer: 0},
{question: "What is the International Air Transport Association airport code for Heathrow Airport?",
  answers: ["HRW","HTR","LHR","LHW"],
  answer: 2},
{question: "The reactor at the site of the Chernobyl nuclear disaster is now in which country?",
  answers: ["Ukraine","Slovakia","Hungary","Russia"],
  answer: 0},
{question: "Which volcano is best known for its eruption in AD 79 that led to the destruction of the Roman cities of Pompeii and Herculaneum?",
  answers: ["Mount Etna","Mount Stromboli","Mount Vesuvius","Mount Vulture"],
  answer: 2},
{question: "The British Naval Ensign features a Union Jack in which corner?",
  answers: ["Top left","Top right","Bottom left","Bottom right"],
  answer: 0},
{question: "Which castle was the childhood home of Elizabeth Bowes-Lyon, the late Queen Mother?",
  answers: ["Craigievar Castle","Glamis Castle","Invergarry Castle","Loch Leven Castle"],
  answer: 1},
{question: "Which countries comprise The British Isles?",
    answers: ["England","England and Wales","England, Scotland and Wales","England, Scotland, Wales, Ireland"],
    answer: 3},
{question: "What is the name given to the part of the North Sea between Lincolnshire and Norfolk?",
    answers: ["The Fen Marshes","The Humber Estuary","The Lincolnshire Fens","The Wash"],
    answer: 3},
{question: "What is the capital of the Republic of Ireland?",
    answers: ["Belfast","Cork","Dublin","Galway"],
    answer: 2},
{question: "What is the longest river (entirely) in England?",
    answers: ["Medway","Severn","Stour","Thames"],
    answer: 3},
{question: "What is the name of the highest peak in the Grampian Mountains?",
    answers: ["Ben Nevis","Cross Fell","Scafell Pike","Snowdon"],
    answer: 0},
{question: "What is the name of the popular seaside resort that is 10 miles North of Lowestoft?",
    answers: ["Clacton-On-Sea","Cromer","Great Yarmouth","Skegness"],
    answer: 2},
{question: "What is the name of the large island joined to the Welsh mainland by the Menai Bridge?",
    answers: ["Anglesey","Holyhead","Isle of Wight","Isle of Skye"],
    answer: 0},
{question: "Born as Harry Webb, who became known as the 'Peter Pan of Pop'?",
    answers: ["Adam Faith","Alvin Stardust","Cliff Richard","Tom Jones"],
    answer: 2},
{question: "'I Predict A Riot' was a hit in 2005 for which pop band?",
    answers: ["Kasabian","Kaiser Chiefs","Pet Shop Boys","Take That"],
    answer: 1},
{question: "Joe Strummer, Mick Jones, Topper Headon and Paul Simenon were which pop band?",
    answers: ["The Clash","The Rolling Stones","The Shadows","The Who"],
    answer: 0},
{question: "Which pop group, led by Justin Hawkins, originated in Lowestoft?",
    answers: ["The Brightness","The Darkness","The Dead Of Night","The Shade"],
    answer: 1},
{question: "Pop singer, guitarist and songwriter Robert Smith founded which group?",
    answers: ["The Answer","The Cure","The Remedy","The Solution"],
    answer: 1},
{question: "Which singer fronted the pop band Duran Duran?",
    answers: ["Martin Fry","Robert Smith","Simon Le Bon","Tony Hadley"],
    answer: 2},
{question: "Which pop group had numerous 1960s hits with songs written by Brian Wilson?",
    answers: ["The Four Seasons","The Kinks","The Beach Boys","Small Faces"],
    answer: 2},
{question: "From which part of Britain does the pop band Stereophonics hail?",
    answers: ["London","Scotland","Manchester","Wales"],
    answer: 3},
{question: "Who recorded 'Ebony and Ivory' in 1982 with Paul McCartney?",
    answers: ["Barry White","Michael Jackson","Ray Charles","Stevie Wonder"],
    answer: 3},
{question: "Which pop singer starred alongside Kevin Costner in the film 'The Bodyguard'?",
    answers: ["Celine Dion","Diana Ross","Janet Jackson","Whitney Houston"],
    answer: 3},
{question: "Which member of The Beatles replaced previous member Pete Best?",
    answers: ["George Harrison","John Lennon","Ringo Starr","Paul McCartney"],
    answer: 2},
{question: "What were the names of the two male members of pop group Abba?",
    answers: ["Benny and Leo","Bjarne and Bobby","Benny and Bjorn","Bernard and Billy"],
    answer: 2},
{question: "Which was Robbie Williams' first top ten solo pop single?",
    answers: ["Angels","Forever Love","Freedom","How Deep Is Your Love"],
    answer: 2},
{question: "With which American rock group did Gene Simmons play?",
    answers: ["Blue Oyster Cult","Guns 'N Roses","Kiss","Ramones"],
    answer: 2},
{question: "Which pop act topped the charts with 'Setting Sun' in 1996?",
    answers: ["Prodigy","The Chemical Brothers","Underworld","Orbital"],
    answer: 1},
{question: "Which American pop singer had hits with 'Runaway' and 'Swiss Maid'?",
    answers: ["Bobby Vee","Del Shannon","Freddy Cannon","Johnny Tillotson"],
    answer: 1},
{question: "Which pop group was fronted by Richard Ashcroft?",
    answers: ["The Verve","Radiohead","Pulp","Manic Street Preachers"],
    answer: 1},
{question: "Orecchietta is pasta in what sort of shapes?",
    answers: ["Ears","Parcels","Spirals","Tubes"],
    answer: 0},
{question: "What is the traditional topping on a Lancashire Hotpot?",
    answers: ["Breadcrumbs","Dumplings","Mashed Potato","Sliced Potato"],
    answer: 3},
{question: "What is Wasabi?",
    answers: ["Brazilian Root Vegetable","Chinese Mushroom","Hawaiian Fruit","Japanese Horseradish"],
    answer: 3},
{question: "By what name do we normally refer to the Chinese Gooseberry?",
    answers: ["Kiwi Fruit","Mango","Passion Fruit","Star Fruit"],
    answer: 0},
{question: "What is the main ingredient of Baba Ghanoush?",
    answers: ["Aubergine","Celeriac","Courgette","Fennel"],
    answer: 0},
{question: "Which herb is used to make Pesto?",
    answers: ["Basil","Dill","Mint","Tarragon"],
    answer: 0},
{question: "From what fruit is the liqueur Crème De Cassis produced?",
    answers: ["Blackcurrant","Cherry","Raspberry","Sloe"],
    answer: 0},
{question: "What is the Mexican avocado dip flavoured with lime, coriander & spice?",
    answers: ["Guacamole","Salsa","Satay","Taramasalata"],
    answer: 0},
{question: "What is the name of the ice cream dessert which is encased in meringue?",
    answers: ["Eton Mess","Baked Alaska","Knickerbocker Glory","Tiramisu"],
    answer: 1},
{question: "From which country does Mavrud wine originate?",
    answers: ["Romania","Bulgaria","South Africa","Chile"],
    answer: 1},
{question: "What gives Mead its flavour?",
    answers: ["Ginger","Mint","Honey","Rose Hips"],
    answer: 2},
{question: "What nickname is often applied to an amateur radio operator?",
    answers: ["Ham","Sam","Spam","Tam"],
    answer: 0},
{question: "What is the usual voltage used on electric model railways?",
    answers: ["6v DC","12v DC","18v DC","24v DC"],
    answer: 1},
{question: "In 1913 the New York World newspaper published the first example of what type of puzzle?",
    answers: ["Sudoku","Anagram","Crossword","Wordsearch"],
    answer: 2},
{question: "What is the name of the slot car racing brand introduced in 1961?",
    answers: ["Scalectric","Scalectrix","Scalextric","Scalextrix"],
    answer: 2},
{question: "What name is given to the art of fine handwriting?",
    answers: ["Callanetics","Calligraphy","Campanology","Chiropody"],
    answer: 1},
{question: "What name is given to the art of fine handwriting?",
    answers: ["Callanetics","Calligraphy","Campanology","Chiropody"],
    answer: 1},
{question: "In which century did the Italian painter, Titian, produce his most famous works?",
    answers: ["13th century","16th century","18th century","19th century"],
    answer: 1},
{question: "Which two countries fought at the Battle of Agincourt, 1415?",
    answers: ["England and France","England and Spain","France and Netherlands","France and Prussia"],
    answer: 0},
{question: "In which South American country did the Incas establish their capital?",
    answers: ["Chile","Colombia","Ecuador","Peru"],
    answer: 3},
{question: "Which 51-mile waterway opened to traffic in August 1914?",
    answers: ["Manchester Ship Canal","Panama Canal","St Lawrence Seaway","Suez Canal"],
    answer: 1},
{question: "Which country was attacked by the Soviet Union on 30 November 1939?",
    answers: ["Denmark","Finland","Norway","Poland"],
    answer: 1},
{question: "Which country was partitioned by Austria, Russia and Prussia throughout the 1800s?",
    answers: ["Finland","Poland","Romania","Switzerland"],
    answer: 1},
{question: "Which European country was ruled by Francisco Franco between 1939 and 1975?",
    answers: ["Italy","Malta","Portugal","Spain"],
    answer: 3},
{question: "How was the 'Kingdom of Serbs, Croats and Slovenes' re-named in 1929?",
    answers: ["Bulgaria","Czechoslovakia","Romania","Yugoslavia"],
    answer: 3},
{question: "How is the line of zero degrees longitude commonly known?",
    answers: ["Arctic Circle","Equator","Greenwich Meridian","Tropic Of Cancer"],
    answer: 2},
{question: "What word describes a very deep and narrow river valley?",
    answers: ["Canyon","Ravine","Rift","Vale"],
    answer: 0},
{question: "What lines on maps join points of similar height?",
    answers: ["Bridle paths","Contour lines","Grid references","Isobars"],
    answer: 1},
{question: "What stretch of a river is the final stage before reaching the river mouth?",
    answers: ["Channel","Delta","Estuary","Tributary"],
    answer: 2},
{question: "What makes a pine cone open and close?",
    answers: ["Temperature","Light","Humidity","Atmospheric pressure"],
    answer: 2},
{question: "Which gas is the most prevalent in the atmosphere?",
    answers: ["Oxygen","Nitrogen","Carbon dioxide","Hydrogen"],
    answer: 1},
{question: "The Tropic of Cancer is where?",
    answers: ["North of the Equator","South of the Equator","On the Equator","Both sides of the Equator"],
    answer: 0},
{question: "From which country does Samba music originate?",
    answers: ["Spain","Argentina","Cuba","Brazil"],
    answer: 3},
{question: "'Orpheus In The Underworld' included which famous dance music?",
    answers: ["Bolero","Bossa Nova","Can-Can","Charleston"],
    answer: 2},
{question: "What timing is used in Foxtrot dance music?",
    answers: ["3/4","4/4","4/8","7/8"],
    answer: 1},
{question: "During which Eurovision Song Contest was 'Riverdance' first performed?",
    answers: ["1986","1990","1994","1998"],
    answer: 2},
{question: "Who composed 'The Nutcracker'?",
    answers: ["Beethoven","Handel","Tchaikovsky","Mozart"],
    answer: 2},
{question: "Which dinosaur's name means 'roof lizard'?",
    answers: ["Pteradactyl","Stegosaurus","Triceratops","Tyrannosaurus"],
    answer: 1},
{question: "Which football club moved to Milton Keynes to eventually form 'MK Dons'?",
    answers: ["Gloucester United FC","St Leonards FC","Telford United FC","Wimbledon FC"],
    answer: 3},
{question: "Blue Mountain Coffee comes from where?",
    answers: ["Colombia","Costa Rica","Jamaica","Kenya"],
    answer: 2},
{question: "Blue Mountain Coffee comes from where?",
    answers: ["Colombia","Costa Rica","Jamaica","Kenya"],
    answer: 2},
{question: "In the bible, who was found in a basket amongst the bullrushes?",
    answers: ["Joseph","Jonah","Levi","Moses"],
    answer: 3},
{question: "What is the capital of New Zealand?",
    answers: ["Auckland","Christchurch","Tauranga","Wellington"],
    answer: 3},
{question: "What is the capital of New Zealand?",
    answers: ["Auckland","Christchurch","Tauranga","Wellington"],
    answer: 3},
{question: "Who performed 'Maybellene', 'Roll over Beethoven', 'Rock and Roll Music' and 'Johnny B Goode' during the 1950s?",
    answers: ["B B King","Chuck Berry","Fats Domino","Ray Charles"],
    answer: 1},
{question: "Who performed 'Maybellene', 'Roll over Beethoven', 'Rock and Roll Music' and 'Johnny B Goode' during the 1950s?",
    answers: ["Jerry Lee Lewis","Chuck Berry","Fats Domino","Ray Charles"],
    answer: 1},
{question: "In which film does an English teacher tell the students that they may call him 'O Captain! My Captain!''?",
    answers: ["Dead Poets Society","Educating Rita","Good Will Hunting","The Graduate"],
    answer: 0},
{question: "Where is the largest expanse of medieval stained glass in the world?",
    answers: ["Lincoln Cathedral","Sistine Chapel","York Minster","Westminster Cathedral"],
    answer: 2},
{question: "Which is the only Portuguese speaking country in the Americas?",
    answers: ["Argentina","Columbia","Brazil","Peru"],
    answer: 2},
{question: "Which is the only Portuguese speaking country in the Americas?",
    answers: ["Argentina","Columbia","Brazil","Peru"],
    answer: 2},
{question: "How many keys does a modern piano have?",
    answers: ["85","86","87","88"],
    answer: 3},
{question: "In a rainbow, what colour is the outer part of the arch?",
    answers: ["Orange","Red","Violet","Yellow"],
    answer: 1},
{question: "Which chambers in a human heart collect blood from an atrium?",
    answers: ["Barnacles","Chronicles","Clavicles","Ventricles"],
    answer: 3},
{question: "In Greek and Roman mythology, a multi-headed hound which guards the gates of Hades is called what?",
    answers: ["Barabas","Cerberus","Pluto","Echidna"],
    answer: 1},
{question: "Who is the King of the Gods in Greek Mythology?",
    answers: ["Apollo","Dionysus","Poseidon","Zeus"],
    answer: 3},
{question: "A squirrel's nest is called a what?",
    answers: ["Eyrie","Drey","Form","Sett"],
    answer: 1},
{question: "What is Harry's surname in the 'Dirty Harry' film series?",
    answers: ["Carnegie","Callahan","Colt","Crown"],
    answer: 1},
{question: "David Howell Evans is more widely known by which stage name?",
    answers: ["The Cliff","The Edge","The Line","The Wall"],
    answer: 1},
{question: "Sports car manufacturer Ferrari are based where?",
    answers: ["Madrid, Spain","Malmo, Sweden","Maranello, Italy","Montevideo, Uruguay"],
    answer: 2},
{question: "Sports car manufacturer Ferrari are based where?",
    answers: ["Madrid, Spain","Malmo, Sweden","Maranello, Italy","Montevideo, Uruguay"],
    answer: 2},
{question: "Who is 'Ben', as sung by Michael Jackson?",
    answers: ["His pet rat","His pet dog","His brother","His imaginary friend"],
    answer: 0},
{question: "In 'The Wizard of Oz' what is the name of the Good Witch?",
    answers: ["Gaynor","Glenda","Glinda","Gloria"],
    answer: 2},
{question: "Who portrayed the character 'Max Headroom'?",
    answers: ["Arnold Schwarzenegger","Christopher Lambert","Harrison Ford","Matt Frewer"],
    answer: 3},
{question: "In which American state is Lake Allatoona?",
    answers: ["Alabama","Colorado","Delaware","Georgia"],
    answer: 3},
{question: "In Star Trek, what is Captain Kirk's middle name?",
    answers: ["Tadleigh","Taliesin","Tiberius","Thaddeus"],
    answer: 2},
{question: "What does 'Hong Kong' translate to in English?",
    answers: ["Happy Island","Fragrant Harbour","High Peak","Land of Wealth"],
    answer: 1},
{question: "In which year did Channel 4 begin broadcasting in the UK?",
    answers: ["1972","1977","1982","1987"],
    answer: 2},
{question: "In which service did John F Kennedy serve during World War Two?",
    answers: ["United States Air Force","United States Army","United States Marine Corps","United States Navy"],
    answer: 3},
{question: "Dry air contains roughly what percentage of nitrogen by volume?",
    answers: ["28","38","58","78"],
    answer: 3},
{question: "Which character was lacking a heart in 'The Wizard of Oz'?",
    answers: ["The Lion","The Scarecrow","The Tin Man","Toto"],
    answer: 2},
{question: "The Battle of Trafalgar was fought off the south-west coast of which country?",
    answers: ["England","Italy","Spain","Sweden"],
    answer: 2},
{question: "Who lives in Hundred Acre Wood?",
    answers: ["Basil Brush","Rupert the Bear","Winnie the Pooh","Paddington Bear"],
    answer: 2},
{question: "What is the medical term for lockjaw?",
    answers: ["Mumps","Rubella","Tetanus","Smallpox"],
    answer: 2},
{question: "What sport is played at Hogwarts?",
    answers: ["Quadrant","Quicket","Quoits","Quidditch"],
    answer: 3},
{question: "Who voiced the cartoon character Bugs Bunny?",
    answers: ["Dan Castellaneta","Don Messick","Joseph Barbera","Mel Blanc"],
    answer: 3},
{question: "Scurvy is a disease resulting from a deficiency of what?",
    answers: ["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],
    answer: 2},
{question: "Quadrophenia is the sixth studio album by which English rock band?",
    answers: ["The Rolling Stones","The Who","The Jam","The Clash"],
    answer: 1},
{question: "Which of these London parks has no lakes?",
    answers: ["Green Park","Hyde Park","Regent's Park","St James's Park"],
    answer: 0},
{question: "What is Arnold Schwarzenegger's middle name?",
    answers: ["Alan","Albert","Alfred","Alois"],
    answer: 3},
{question: "Which football club has the nickname 'The Blades'?",
    answers: ["Scunthorpe United","Sheffield United","Sheffield Wednesday","Southampton"],
    answer: 1},
{question: "Hypophosphatasia affects what part of the body?",
    answers: ["Blood","Bones","Muscles","Nerves"],
    answer: 1},
{question: "Which of these colours is not a primary colour?",
    answers: ["Red","Blue","Green","Yellow"],
    answer: 2},
{question: "What was the name of the Skye Terrier whose statue stands near his master's grave in Edinburgh?",
    answers: ["Blackfriars Bobby","Greenfriars Bobby","Greyfriars Bobby","Whitefriars Bobby"],
    answer: 2},
{question: "What is the collective noun for a group of cats?",
    answers: ["A chowder","A clowder","A crowder","A herd"],
    answer: 1},
{question: "The Manx cat is often born without what?",
    answers: ["Claws","Hair","A tail","Whiskers"],
    answer: 2},
{question: "In Alice in Wonderland, what is the name of the cat that can appear and disappear at will?",
    answers: ["Derbyshire Cat","Cheshire Cat","Lancashire Cat","Yorkshire Cat"],
    answer: 1},
{question: "In Alice in Wonderland, what is the name of the cat that can appear and disappear at will?",
    answers: ["Derbyshire Cat","Cheshire Cat","Lancashire Cat","Yorkshire Cat"],
    answer: 1},
{question: "In which year was the film 'Jurassic Park' released?",
    answers: ["1992","1993","1994","1995"],
    answer: 1},
{question: "Which actor appeared alongside Tom Cruise in 'A Few Good Men'?",
    answers: ["Al Pacino","Dustin Hoffman","Jack Nicholson","Michael Douglas"],
    answer: 2}
];










  // http://www.pubquizarea.com/
